# Generated by Django 5.1.2 on 2024-10-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'بیمار', 'verbose_name_plural': 'بیماران'},
        ),
        migrations.AlterField(
            model_name='patient',
            name='code',
            field=models.SmallIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
