# Generated by Django 5.1.2 on 2024-10-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_module', '0002_alter_patient_options_alter_patient_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='code',
            field=models.SmallIntegerField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
