# Generated by Django 5.1.2 on 2024-10-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_module', '0003_alter_patient_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
