# Generated by Django 5.1.2 on 2024-10-27 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_module', '0005_alter_patient_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='code',
            field=models.SmallIntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(9)]),
        ),
    ]
