# Generated by Django 5.1.2 on 2024-10-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_module', '0010_patienthealthyinformation_alter_patient_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='سن'),
        ),
    ]
