# Generated by Django 5.1.2 on 2024-10-29 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_module', '0012_patientgender_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_module.patientgender', verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='information',
            field=models.ManyToManyField(blank=True, null=True, to='patient_module.patienthealthyinformation', verbose_name='اطلاعات سوابق بیماری'),
        ),
        migrations.AlterField(
            model_name='patientgender',
            name='title',
            field=models.CharField(max_length=100, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='patienthealthyinformation',
            name='title',
            field=models.CharField(max_length=100, verbose_name='اطلاعات بیماری مریض'),
        ),
    ]
