# Generated by Django 5.1.2 on 2024-10-25 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='medicine',
            name='short_desc',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='medicine_module.medicinecategory'),
        ),
    ]
