# Generated by Django 5.1.2 on 2024-10-25 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_module', '0002_medicinecategory_alter_medicine_short_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='medicine_module.medicinecategory'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='short_desc',
            field=models.CharField(max_length=100),
        ),
    ]
