# Generated by Django 5.1.2 on 2024-10-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_module', '0003_alter_medicine_category_alter_medicine_short_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name': 'دارو', 'verbose_name_plural': 'دارو ها'},
        ),
        migrations.AlterModelOptions(
            name='medicinecategory',
            options={'verbose_name': 'دسته بندی دارو', 'verbose_name_plural': 'دسته بندی دارو ها'},
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='category',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام دارو'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='short_desc',
            field=models.CharField(max_length=100, verbose_name='توضیحات مصرف'),
        ),
        migrations.AlterField(
            model_name='medicinecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام دسته بندی'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.ManyToManyField(to='medicine_module.medicinecategory', verbose_name='دسته بندی'),
        ),
    ]
