# Generated by Django 5.1.2 on 2024-12-06 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_submitted', models.BooleanField(verbose_name='نهایی شده/نشده')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='تاریخ ایجاد نسخه')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL, verbose_name='نام پزشک')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL, verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'نسخه دارو بیمار',
                'verbose_name_plural': 'نسخه های دارو بیماران',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='تعداد')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_module.medicine', verbose_name='دارو')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription_module.prescription', verbose_name='نسخه دارو')),
            ],
            options={
                'verbose_name': 'جزئیات نسخه دارو ها',
                'verbose_name_plural': 'لیست جزئیات نسخه دارو',
            },
        ),
    ]
